name: Playwright Tests

on:
  push:
    branches:
    - main

jobs:
  e2e:
    name: Mercedes Benz Playwright Tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install NPM Packages
        run: npm ci
      - name: Install Playwright Browsers & Dependencies
        run: npx playwright install --with-deps
      - name: Run E2E Tests
        run: npx playwright test
        env:
          HOME: /root
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
